### PR TITLE
Bump to Scala 2.10.3-RC3

### PR DESCRIPTION
**Pull request by retronym**
We needed an RC3. @jsuereth, can we please have corresponding a release this project to enable the IDE build?

I'll comment here when I've release the Scala artifacts to Maven, should be within 2 hours.

### CODE REVIEW

**Comment by jsuereth** [comment]
Great.  I may just branch/tag directly from the RC3 tag so we aren't using the latest integration branches (for 2.10.4)

**Comment by retronym** [comment]
Scala artifacts are now on Sonatype: https://oss.sonatype.org/index.html#nexus-search;gav~org.scala-lang*~~2.10.3-RC3~~

I would appreciate if this release could be ready for the IDE team to build off by tomorrow.

**Comment by jsuereth** [comment]
no problem. I'm trying to tackle it now :)

**Comment by jsuereth** [comment]
See the tag https://github.com/typesafehub/sbt-builds-for-ide/tree/v0.13.0-on-2.10.3-RC3

**Comment by jsuereth** [comment]
Result of publishing here.  Should be done in < an hour.  https://jenkins-dbuild.typesafe.com:8499/job/sbt-nightly-for-ide-on-scala-2.10.3/68/console

**Comment by retronym** [comment]
Legend. Thanks.

**Pull request merged**
