### PR TITLE
Align sbt build for IDE and nightly build.

### PR DESCRIPTION
**Pull request by adriaanm**
[Merge https://github.com/harrah/sbinary/pull/9 first!]

The only difference between the two builds is the vars section.
Ideally, these would be stored in properties file,
so that we can have only one dbuild config.

Build scalacheck (could also resolve it like scala-xml etc),
so we can run SBinary's test suite.

Also upgrade to M7 versions.properties.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
@adriaanm Please sign the latest Typesafe Contributors License Agreement so that we can review and hopefully merge this Pull Request:
[http://typesafe.com/contribute/cla](http://typesafe.com/contribute/cla)

**Comment by adriaanm** [comment]
btw, why are not all of the sbt subprojects run?

**Comment by adriaanm** [comment]
review by @jsuereth

**Comment by adriaanm** [comment]
this should be ready to go, but best to trigger a build and make sure it worked, as I only tested locally

**Comment by jsuereth** [comment]
Rawk.  This looks great.   I need to cut some releases today so I'll be looking into this more in depth, but it appears to build :)

**Pull request merged**
