### PR TITLE
Fixes for scala 2.11 modularization

### PR DESCRIPTION
**Pull request by jsuereth**
Note: The build actually needs to change for the latest Scala 2.11 branch (once modularization is fixed).

This makes use of the fixes here:

https://github.com/typesafehub/distributed-build/pull/47

And fixes our build so this can get merged:

https://github.com/scala/scala/pull/2855

Assuming this is merged first:

https://github.com/adriaanm/scala/pull/7

In particular, this uses another temporary dbuild release (pending review of improvements) and a branch for scala which includes the dbuild-meta.json fixes.   Those will have to point back at scala/scala.git#master before merging.

Also, we removed resolving Scala via ivy for now.   There is no way to construct a complete scala-home in dbuild's sbt rewriting.   It should be innocuous to rebuild scala here, as binary compatibilty should remain in place for the potential few hour difference between build.

Also, if this is going to be used by PR validation, then we'll have to try out the partial support for PR references, see:

https://github.com/typesafehub/distributed-build/issues/35

Reivew by @dragos and @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
running dbuild against this locally -- looking good so far

**Comment by adriaanm** [comment]
WOOT!

```
[info] ---==  Execution Report ==---
[info] Report from the dbuild run for dbuild:
[info] Project scala-lib--------------: SUCCESS (project rebuilt ok)
[info] Project scala-actors-----------: SUCCESS (project rebuilt ok)
[info] Project scala-reflect----------: SUCCESS (project rebuilt ok)
[info] Project scala-xml--------------: SUCCESS (project rebuilt ok)
[info] Project scala-parser-combinators: SUCCESS (project rebuilt ok)
[info] Project scala-compiler---------: SUCCESS (project rebuilt ok)
[info] Project sbinary----------------: SUCCESS (project rebuilt ok)
[info] Project sbt--------------------: SUCCESS (project rebuilt ok)
[info] Project sbt-republish----------: SUCCESS (project rebuilt ok)
[info] Project zinc-------------------: SUCCESS (project rebuilt ok)
[info] >>> The dbuild result is-----------: SUCCESS (project rebuilt ok)
[info] ---==  End Execution Report ==---
[info] --== Done Console Notifications ==--
[info] ---==  Tasks Report ==---
[info] Successful: Deploy, Notifications
[info] ---==  End Tasks Report ==---
Result: SUCCESS (project rebuilt ok)
Build succeeded after: 00h 15m 02.6s
All done.
### dbuild SUCCESS !
```

**Comment by jsuereth** [comment]
RAWK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!111111111111111111111111111111111111111111111111ONEONEONEONEONEONE1111111111111111111111111!!!!!!!!!!!!!!!!!!!!!!!!!!11111111111111ONE!11!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by adriaanm** [comment]
and:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.scala-ide.sdt.build ........................... SUCCESS [0.805s]
[INFO] org.scala-ide.sdt.aspects ......................... SUCCESS [7.272s]
[INFO] org.scala-ide.sdt.core ............................ SUCCESS [57.434s]
[INFO] org.scala-ide.sdt.core.tests ...................... SUCCESS [2:34.022s]
[INFO] org.scala-ide.sdt.spy ............................. SUCCESS [5.658s]
[INFO] org.scala-ide.sdt.debug ........................... SUCCESS [15.632s]
[INFO] org.scala-ide.sdt.debug.tests ..................... SUCCESS [1:11.847s]
[INFO] org.scala-ide.sdt.weaving.feature ................. SUCCESS [0.473s]
[INFO] org.scala-ide.sdt.feature ......................... SUCCESS [0.366s]
[INFO] org.scala-ide.sdt.dev.feature ..................... SUCCESS [0.366s]
[INFO] org.scala-ide.sdt.source.feature .................. SUCCESS [0.266s]
[INFO] org.scala-ide.sdt.update-site ..................... SUCCESS [4.373s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:46.171s
[INFO] Finished at: Fri Sep 06 13:48:44 PDT 2013
[INFO] Final Memory: 98M/205M
[INFO] ------------------------------------------------------------------------
### SCALA-IDE SUCCESS !
```

**Comment by adriaanm** [comment]
can I haz merge?

**Comment by jsuereth** [comment]
Our nightly will fail until the scala 2.11.0-SNAPSHOT Has the module config.  So no, I'll wait for the nightly (unless the above is using a public 2.11.0-SNAPSHOT

**Comment by jsuereth** [comment]
Cool!  Fixes look great.  Thanks everyone, we're merging this now for the new modules.  Go progress!

**Pull request merged**
