### PR TITLE
Switch to Scala 2.10.5-SNAPSHOT builds

### PR DESCRIPTION
**Pull request by gkossakowski**
Scala 2.10.4 final has been released. We are building 2.10.5-SNAPSHOTs now.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @jsuereth

**Comment by jsuereth** [comment]
Thanks for the fix!  I'll merge for now, with the caveat that we're still trying to move to uber-build.  (see https://github.com/scala-ide/uber-build/pull/41)

**Comment by gkossakowski** [comment]
Thanks! Will scala-ide/uber-build#41 fix the problem of relying on hardcoded SNAPSHOT versions that tend to go stale?

**Comment by jsuereth** [comment]
Sort of.  For nightlies we could just re-build Scala and see if we still work.  Otherwise, we rely on version numbers being in sync.

**Comment by gkossakowski** [comment]
I see. I'll keep an eye on scala-ide/uber-build#41 then.

**Pull request merged**
