### PR TITLE
Revert breaks, create new script for new stuff.

### PR DESCRIPTION
**Pull request by jsuereth**
Review by @adriaanm, @retronym @gkossakowski @skyluc @dotta

### CODE REVIEW

**Comment by dotta** [comment]
If I understood the changes in this PR, after merging:
- Use Sbt 0.13.0 in the Scala PR validator job.
- Publish sbt artifacts for Sbt 0.13.2-M1 built for 2.10.4-SNAPSHOT

This means there won't be a Sbt 0.13.0 built for 2.10.4-SNAPSHOT anymore. Correct?

EDIT:

So, if you guys no longer plan to publish Sbt 0.13.0 builds for 2.10.4-SNAPSHOT, then we need to change our build to use different Sbt version when building against 2.10.4-SNAPSHOT and 2.11.0-SNAPSHOT. In fact, at the moment we are using 0.13.0 for both, as you can see for yourself [here](https://github.com/scala-ide/scala-ide/blob/master/pom.xml#L68). Having a different Sbt version for each Scala major version is a bit of a pain for us, as this will undoubtedly get out of sync. Hence, I'd prefer if you could use the same Sbt version for both 2.10.4-SNAPSHOT and 2.11.0-SNAPSHOT.

\cc @dragos

**Comment by adriaanm** [comment]
@dotta, my understanding of the intent of this PR is that it reverts back to the state of Dec 12, so building 0.13.0 for 2.11 and 2.10. It adds a new config sbt-0.13.x-on-2.10.x, that builds 0.13.2-M2 on 2.10.4-SNAPSHOT

**Comment by jsuereth** [comment]
Umm, this is not the intent at all.  With this change we'll publish BOTH snapshots, with different version numbers.

For the _NEW_ version, we'll only be publishing Scala 2.10.4-SNAPSHOT versions until the build is up-to-snuff for Scala 2.11.

**Comment by adriaanm** [comment]
Sorry I don't understand your comment -- for my understanding, could you correct the errors in my comment and specify for each "Snapshot/version" in your comment, which project you're talking about (sbt/scala)?

When looking at the files changed, it seems my comment was accurate:
-  sbt-on-2.10.x does `set-version: "0.13.0-on-"${vars.scala-version}"-for-IDE-SNAPSHOT"` for `scala-version: "2.10.4-SNAPSHOT"` (using sbt tag `v0.13.0`)
-  sbt-0.13.x-on-2.10.x has `sbt-version: "0.13.2-M1"` (ok, not -M2 as I said) 
- sbt-on-2.11.x builds the special branch for 2.11 integration on 2.11, setting sbt's version to `"0.13.0"${vars.sbt.branch.prefix}"-on-"${vars.maven.version.number}${vars.sbt.version.suffix}"-SNAPSHOT"`

My summary was also what I think should happen. As far as I understand, it should be the fastest way to unblock the IDE and Scala teams.

**Comment by jsuereth** [comment]
`sbt-on-2.11.x` should have the same version semantics as`sbt-on-2.10.x`.  I'll fix that up.  Also, I misread your original comment, sorry.

**Comment by jsuereth** [comment]
Ok, merging these for tonight's nightly. I _think_ we are all in agreement this is the right way to go.

**Comment by dotta** [comment]
:+1: 

@adriaanm I was looking at the wrong script :S You were right, of course.

**Pull request merged**
