### PR TITLE
Fix current nightlies.

### PR DESCRIPTION
**Pull request by jsuereth**
- Keep zinc + sbt branches synched.  We can't use stable sbt + unstable zinc for IDE/Scala builds.  Migrate to both stable.
- Create new build files for all unstable branches (to catch issues between inc. compiler changes + zinc
- Upgrade to dbuild 0.6.5.

Review by @harrah / @cunei 

cc> @retronym @adriaanm @gkossakowski @dragos - and sorry for the breakage.

### CODE REVIEW

**Comment by jsuereth** [comment]
Also, this appears to work well (2/5 builds checked):

```
[info] Report from the dbuild run for dbuild: 
[info] Project scala-lib---------------: SUCCESS (project rebuilt ok)
[info] Project scala-xml---------------: SUCCESS (project rebuilt ok)
[info] Project scala-actors------------: SUCCESS (project rebuilt ok)
[info] Project scala-reflect-----------: SUCCESS (project rebuilt ok)
[info] Project scala-parser-combinators: SUCCESS (project rebuilt ok)
[info] Project scala-compiler----------: SUCCESS (project rebuilt ok)
[info] Project sbinary-----------------: SUCCESS (project rebuilt ok)
[info] Project sbt---------------------: SUCCESS (project rebuilt ok)
[info] Project sbt-republish-----------: SUCCESS (project rebuilt ok)
[info] Project zinc--------------------: SUCCESS (project rebuilt ok)
[info] >>> The dbuild result is------------: SUCCESS (project rebuilt ok)
[info] ---==  End Execution Report ==---
[info] --== Done Console Notifications ==--
[info] ---==  Tasks Report ==---
[info] Successful: Deploy, Notifications
[info] ---==  End Tasks Report ==---
Result: SUCCESS (project rebuilt ok)
```

**Comment by cunei** [comment]
LGTM

**Comment by gkossakowski** [comment]
@jsuereth: thanks!

**Comment by dragos** [comment]
Note that this is only for nightlies. Which one should the PR-validation script use? See [this line](https://github.com/scala-ide/uber-build/blob/master/uber-build.sh#L831). /cc @skyluc

**Comment by jsuereth** [comment]
the same one it does now.  See the README.md

**Comment by dragos** [comment]
Oh, sorry I missed that. Thanks!

**Pull request merged**
